services:
  postgres:
    image: "postgres:17.2" # Usa una imagen ya creada
    container_name: db_
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - network
  api:
    container_name: api_
    build: ./api
    environment: # Variables de entorno para la conexión a la base de datos
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres # Que este servicio espere a que el servicio de base de datos este listo
    volumes:
      - ./api:/app
    networks:
      - network

volumes:
  db_data: # Volumen para persistir los datos de la base de datos
networks:
  network: # Red para conectar los contenedores entre si internamente
    driver: bridge
