services:
  postgres:
    image: "postgres:17.2"
    container_name: db_
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - network
  api:
    container_name: api_
    build: ./api
    environment:
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./api:/app
    networks:
      - network

volumes:
  db_data:
networks:
  network:
    driver: bridge
